# Generated by Django 3.1.2 on 2020-10-23 14:01
from django.contrib.auth.models import User
from django.db import migrations
from django.utils import timezone

def create_default_user(apps, schema_editor):
    new_user = {
        'username': 'Default User',
        'email': 'default.user@mystore.com',
        'password': 'my_store_secret',
        'last_login': timezone.now()
    }

    if not User.objects.filter(username=new_user['username']).first():
        default_user = User.objects.create_user(**new_user)
        default_user.save()

class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
         migrations.RunPython(create_default_user),
    ]
